# Generated by Django 3.2.7 on 2021-09-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatroom', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('is_readed_by_receiver', models.BooleanField(default=False)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='accounts.account')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatroom.chatroom')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='accounts.account')),
            ],
        ),
    ]
